spring:
  config:
    activate:
      on-profile: default
  batch:
    job:
      enabled: false
  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true

  freemarker:
    suffix: .ftl

  web:
    resources:
      static-locations: classpath:/static/

custom:


---
