spring:
  config:
    activate:
      on-profile: default

  datasource:
    driver-class-name: org.h2.Driver
    hikari:
      jdbc-url: jdbc:h2:mem:testdb
      username: sa
      password:
  jpa:
    database: h2
    hibernate:
      ddl-auto: create
    show-sql: true
#    defer-datasource-initialization: true
#  sql:
#    init:
#      data-locations:
#      - 'classpath:import.sql'
---
